# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget ssnet::ssnetwork ssnet::sstcp_bit_test ssnet::protobit_test ssnet::sstcp_proto_test ssnet::mersenne_test ssnet::protocol_test ssnet::sstcp_test)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  unset(_targetsDefined)
  unset(_targetsNotDefined)
  unset(_expectedTargets)
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# Create imported target ssnet::ssnetwork
add_library(ssnet::ssnetwork STATIC IMPORTED)

set_target_properties(ssnet::ssnetwork PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/lovebc/Desktop/workspace/ros/lab_car_ws/src/bitrobot/lib/repo-v0.0.4/cpp/ssnet"
)

# Create imported target ssnet::sstcp_bit_test
add_executable(ssnet::sstcp_bit_test IMPORTED)

# Create imported target ssnet::protobit_test
add_executable(ssnet::protobit_test IMPORTED)

# Create imported target ssnet::sstcp_proto_test
add_executable(ssnet::sstcp_proto_test IMPORTED)

# Create imported target ssnet::mersenne_test
add_executable(ssnet::mersenne_test IMPORTED)

# Create imported target ssnet::protocol_test
add_executable(ssnet::protocol_test IMPORTED)

# Create imported target ssnet::sstcp_test
add_executable(ssnet::sstcp_test IMPORTED)

# Import target "ssnet::ssnetwork" for configuration "Debug"
set_property(TARGET ssnet::ssnetwork APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(ssnet::ssnetwork PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LOCATION_DEBUG "/home/lovebc/Desktop/workspace/ros/lab_car_ws/src/bitrobot/lib/repo-v0.0.4/cpp/build-Debug/ssnet/lib/libssnetwork_d.a"
  )

# Import target "ssnet::sstcp_bit_test" for configuration "Debug"
set_property(TARGET ssnet::sstcp_bit_test APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(ssnet::sstcp_bit_test PROPERTIES
  IMPORTED_LOCATION_DEBUG "/home/lovebc/Desktop/workspace/ros/lab_car_ws/src/bitrobot/lib/repo-v0.0.4/cpp/build-Debug/ssnet/bin/sstcp_bit_test_d"
  )

# Import target "ssnet::protobit_test" for configuration "Debug"
set_property(TARGET ssnet::protobit_test APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(ssnet::protobit_test PROPERTIES
  IMPORTED_LOCATION_DEBUG "/home/lovebc/Desktop/workspace/ros/lab_car_ws/src/bitrobot/lib/repo-v0.0.4/cpp/build-Debug/ssnet/bin/protobit_test_d"
  )

# Import target "ssnet::sstcp_proto_test" for configuration "Debug"
set_property(TARGET ssnet::sstcp_proto_test APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(ssnet::sstcp_proto_test PROPERTIES
  IMPORTED_LOCATION_DEBUG "/home/lovebc/Desktop/workspace/ros/lab_car_ws/src/bitrobot/lib/repo-v0.0.4/cpp/build-Debug/ssnet/bin/sstcp_proto_test_d"
  )

# Import target "ssnet::mersenne_test" for configuration "Debug"
set_property(TARGET ssnet::mersenne_test APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(ssnet::mersenne_test PROPERTIES
  IMPORTED_LOCATION_DEBUG "/home/lovebc/Desktop/workspace/ros/lab_car_ws/src/bitrobot/lib/repo-v0.0.4/cpp/build-Debug/ssnet/bin/mersenne_test_d"
  )

# Import target "ssnet::protocol_test" for configuration "Debug"
set_property(TARGET ssnet::protocol_test APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(ssnet::protocol_test PROPERTIES
  IMPORTED_LOCATION_DEBUG "/home/lovebc/Desktop/workspace/ros/lab_car_ws/src/bitrobot/lib/repo-v0.0.4/cpp/build-Debug/ssnet/bin/protocol_test_d"
  )

# Import target "ssnet::sstcp_test" for configuration "Debug"
set_property(TARGET ssnet::sstcp_test APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(ssnet::sstcp_test PROPERTIES
  IMPORTED_LOCATION_DEBUG "/home/lovebc/Desktop/workspace/ros/lab_car_ws/src/bitrobot/lib/repo-v0.0.4/cpp/build-Debug/ssnet/bin/sstcp_test_d"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
