<?xml version="1.0"?>

<robot name="pioneer-lx-devil" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- TODO share pioneer lx mobile robot components with pioneer-lx urdf by
including macro. -->
  
  <property name="deck_height" value="0.076" />
  <property name="deck_width" value="0.437" />
  <property name="deck_length" value="0.407" />
  <property name="base_height" value="0.35" />
  <property name="base_width" value="0.50" />
  <property name="base_length" value="0.697" />
  <property name="plinth_width" value="0.5" />
  <property name="plinth_length" value="0.697" /> <!-- at bottom -->
  <property name="plinth_height" value="0.99" /> 
  <property name="plinth_bottom_mount_holes_z" value="0.584" />
  <property name="plinth_middle_mount_holes_z" value="0.73" />
  <property name="plinth_top_mount_holes_z" value="${plinth_height - 0.03}" />
  <property name="arm_mount_offset_z" value="0.076" />   <!-- height of bottom of jaco arm above mounting hole when mounted using supplied 8020 hardware fixtrue -->
  <property name="arm_mount_holes_z" value="${plinth_bottom_mount_holes_z}" /> <!-- change this if you move the arm mounting to one of the other sets of holes -->
  <property name="arm_origin_z" value="${base_height + deck_height + arm_mount_holes_z + arm_mount_offset_z}" />
  <property name="left_arm_origin" value="-0.02 0.184 ${arm_origin_z}" /> <!-- old z was 1.1384 -->
  <property name="right_arm_origin" value="-0.02 -0.184 ${arm_origin_z}" />


  <link name="base_link">

    <!-- base_link origin point is center of rotation, on the floor. -->

    <visual name="base_link_visual">
      <geometry name="base_link_visual_geom">
        <mesh filename="package://amr_robots_description/meshes/pioneer-lx/pioneer-lx_visual.stl" scale="0.001 0.001 0.001" />
        <!-- box size="0.697 0.5 0.333" / -->
      </geometry>
      <origin xyz="0 0 0" rpy="0 0 1.570796" /> 
      <material name="lx_red_mat">
        <color rgba="0.8 0.1 0.1 1.0" />
      </material>
    </visual>

    <collision name="base_link_collision">
      <geometry name="base_link_collision_geom">
        <box size="${base_length} ${base_width} ${base_height}" />
        <!-- box size="0.697 0.5 0.35" / -->
      </geometry>
      <origin xyz="0 0 0.200" rpy="0 0 0" /> 
    </collision>

  </link>

  <!-- for some reason KDL wants this to be a separate link -->
  <link name="robot_mass">
    <inertial>
      <mass value="57.8" /> <!-- 60 kg minus each wheel -->
      <inertia ixx="1" ixy="0" ixz="0" iyy="1" iyz="0" izz="1" />
    </inertial>
  </link>
  <joint name="robot_mass_attach" type="fixed">
    <parent link="base_link" />
    <child link="robot_mass" />
  </joint>


  <!-- right wheel -->

  <link name="r_wheel">

    <inertial>
      <mass value="1.1" />   <!-- kg -->
      <inertia ixx="0.02" ixy="0" ixz="0" iyy="0.02" iyz="0" izz="0.01" />
    </inertial>

<!--
TODO separate out pioner lx wheels in visual model 
    <visual name="r_wheel_dumb_visual">
      <geometry name="r_wheel_dumb_visual_geom">
        <cylinder radius="0.100" length="0.05" />
      </geometry>
      <origin rpy="1.570796 0 0" />
      <material name="lx_grey_mat">
        <color rgba="0.8 0.8 0.8 1.0" />
      </material>
    </visual>
-->
    
    <collision name="r_wheel_collision">
      <geometry name="r_wheel_collision_geom">
        <cylinder radius="0.100" length="0.05" />
      </geometry>
      <origin rpy="1.570796 0 0" />
    </collision>
        
  </link>

  <!-- left wheel -->

  <link name="l_wheel">

    <inertial>
      <mass value="1.1" />   <!-- kg -->
      <inertia ixx="0.02" ixy="0" ixz="0" iyy="0.02" iyz="0" izz="0.01" />
    </inertial>

<!--
    <visual name="l_wheel_dumb_visual">
      <geometry name="l_wheel_dumb_visual_geom">
        <cylinder radius="0.100" length="0.05" />
      </geometry>
      <origin rpy="1.570796 0 0" />
      <material name="lx_grey_mat">
        <color rgba="0.8 0.8 0.8 1.0" />
      </material>
    </visual>
   -->
 
    <collision name="l_wheel_collision">
      <geometry name="l_wheel_collision_geom">
        <cylinder radius="0.100" length="0.05" />
      </geometry>
      <origin rpy="1.570796 0 0" />
    </collision>
        
  </link>

  <!-- wheel joints. only used in gazebo, real robot velocity is controlled as a unit, not individual wheel motion. -->

  <joint name="r_wheel_joint" type="fixed"> <!--  type="continuous" -->
    <origin xyz="0 0.2 0.1" rpy="0 0 0" />
    <parent link="base_link" />
    <child link="r_wheel" />
  </joint>

  <joint name="l_wheel_joint" type="fixed"> <!-- type="continuous" -->
    <origin xyz="0 -0.2 0.1" rpy="0 0 0" />
    <parent link="base_link" />
    <child link="l_wheel" />
  </joint>

  <!-- pioneer lx deck -->
  <link name="deck">
    <visual name="deck_visual">
      <geometry name="deck_visual_geom">
        <box size="${deck_length} ${deck_width} ${deck_height}" />
      </geometry>
      <material name="lx_deck_mat">
        <color rgba="0 0 0 1" />
      </material>
    </visual>
    <collision name="deck_collision">
      <geometry name="deck_collision_geom">
        <box size="${deck_length} ${deck_width} ${deck_height}" />
        <!-- box size="0.407 0.437 0.076" / -->
      </geometry>
    </collision>
  </link>

  <joint name="deck_joint" type="fixed"> 
    <origin xyz="0.075 0 0.410" rpy="0 0 0" />
    <parent link="base_link" />
    <child link="deck" />
  </joint>
  
  


  <!-- "plinth" -->

  <link name="plinth">
  
    <visual name="plinth_visual">
      <geometry name="plinth_visual_geom">
        <mesh filename="package://amr_robots_description/meshes/pioneer-lx/pioneer-lx-plinth.stl" scale="0.001 0.001 0.001" />
        <!-- box size="0.18 0.2476 0.99" / -->
      </geometry>
      <material name="plinth_darkgrey_mat">
        <color rgba="0.2 0.2 0.2 1.0" />
      </material>
    </visual>

    <collision name="plinth_collision">
      <geometry name="plinth_collision_geom">
        <mesh filename="package://amr_robots_description/meshes/pioneer-lx/pioneer-lx-plinth.stl" scale="0.001 0.001 0.001" />
        <!-- box size="0.18 0.2476 0.99" / -->
        <origin xyz="-0.02 0 0.867" />
      </geometry>
    </collision>

  </link>

  <joint name="plinth_joint" type="fixed">
    <parent link="base_link" />
    <child link="plinth" />
    <origin xyz="-0.11 0 0.448" />
  </joint>
  

  <!-- Jaco2 arms, using lower upward-pointing mounting option.

       The kinova_description package is contained in the
       Kinovarobotics jaco_ros repository. As of 2/4/2015, you must 
       check out the "jaco2_import" branch.
        https://github.com/Kinovarobotics/jaco-ros/tree/jaco2_import
   -->

  <xacro:include filename="$(find kinova_description)/urdf/jaco2_arm.xacro" />

  <link name="left_arm_mount">
  </link>

  <link name="right_arm_mount">
  </link>

  <xacro:jaco2_arm parent="left_arm_mount" prefix="left_" />

  <xacro:jaco2_arm parent="right_arm_mount" prefix="right_" />

  <joint name="left_arm_attach" type="fixed">
    <child link="left_arm_mount" />
    <parent link="base_link" />
    <origin xyz="${left_arm_origin}" rpy="0 0 1.5707" />
    <!-- old z was 1.1384 -->
  </joint>

  <joint name="right_arm_attach" type="fixed">
    <child link="right_arm_mount" />
    <parent link="base_link" />
    <origin xyz="${right_arm_origin}" rpy="0 0 1.5707" />
    <!-- old z was 1.1384 -->
  </joint>

 <!-- PTU 
    The flir_ptu_description package is either from system packages in
    /opt/ros/... or from source repository
    https://github.com/ros-drivers/flir_ptu
  -->

  <xacro:include filename="$(find flir_ptu_description)/urdf/d46.urdf.xacro" />
  <ptu_d46 name="ptu" />

  <joint name="ptu_base_mount" type="fixed">
    <parent link="plinth" />
    <child link="ptu_base_link" />
    <origin xyz="0.152 0.03 0.91" /> 
  </joint>


  <!-- kinect -->

  <link name="kinect">
    <visual name="kinect_visual">
      <geometry name="kinect_visual_geom">
        <box size="0.07 0.25 0.065" />
        <origin xyz="0.03 0 0.035" />
      </geometry>
      <material name="kinect_black_mat">
        <color rgba="0.0 0.0 0.0 1.0" />
      </material>
    </visual>
    <collision name="kinect_collision">
      <geometry name="kinect_visual_geom">
        <box size="0.07 0.25 0.065" />
        <origin xyz="0.03 0 0.035" />
      </geometry>
    </collision>
  </link>

  <joint name="kinect_mount" type="fixed">
    <parent link="ptu_mount_link" />
    <child  link="kinect" />
    <origin xyz="0 0 0.0325" />
  </joint>


  <!-- hack for depthimage_to_laserscan (todo: configure depthimage_to_laserscan to use "kinect" as frame -->
  <link name="camera_depth_frame"> 
    <origin xyz="0 0 0" />
    <inertial>
      <mass value="0.0" /> 
      <inertia ixx="1" ixy="0" ixz="0" iyy="1" iyz="0" izz="1" />
    </inertial>
  </link>

  <joint name="camera_depth_frame_joint" type="fixed">
    <parent link="kinect" />
    <child link="camera_depth_frame" />
    <origin xyz="0 0 0" />
  </joint>

</robot>
  

