<?xml version="1.0"?>
<!-- ft: xml -->

<!-- this is originally from ubc-ros-pkg
https://svn.code.sf.net/p/ubc-ros-pkg/code/trunk/robots/powerbot_defs/

It does not have the exact shape of the robot (just blocks) but should be the
right dimensions. 
-->

<robot name="powerbot">

  <property name="M_PI" value="3.1415926535897931" />
  
  <property name="base_size_x" value="0.900" />
  <property name="base_size_y" value="0.680" />
  <property name="base_size_z" value="0.480" />

  <property name="base_height_offset" value="0.07" />
  <property name="base_mass" value="120.0" />


  <property name="base_laser_size_x" value="0.15" />
  <property name="base_laser_size_y" value="0.15" />
  <property name="base_laser_size_z" value="0.15" />

  <property name="base_laser_offset_x" value="0.27" />
  <property name="base_center_offset" value="0.1" />

  <property name="laser_offset" value="0.06" />
  <property name="laser_frame_offset" value="0.11" />

  <material name="Blue">
    <color rgba="0.0 0.0 0.8 1.0"/>
  </material>
  
  
  <material name="Yellow">
    <color rgba="0.9 0.75 0.1 1.0"/>
  </material>
  
  <material name="Black">
    <color rgba="0.0 0.0 0.0 1.0"/>
  </material>

  <!-- Base -->
  
  <link name="base_link">
    <inertial>
      <mass value="${base_mass}" />
      <origin xyz="${base_size_x/2} ${base_size_y/2} ${base_size_z/2}" />
      <inertia ixx="5.652232699207" ixy="-0.009719934438" ixz="1.293988226423"
		iyy="5.669473158652" iyz="-0.007379583694" izz="3.683196351726" />
    </inertial>

    <visual>
      <origin xyz="-${base_center_offset} 0 ${base_size_z/2}" rpy="0 0 0" />
      <geometry name="base_visual_geom">
	<box size="${base_size_x} ${base_size_y} ${base_size_z}" />
      </geometry>
      
      <material name="Yellow" />
    </visual>

    <collision name="base_collision">
      <origin xyz="0 0 ${base_size_z/2}" rpy="0 0 0" />
      <geometry name="base_collision_geom">
	<box size="${base_size_x} ${base_size_y} ${base_size_z}" />
      </geometry>
    </collision>
  </link>



  <!-- Base footprint -->
  <joint name="base_footprint_joint" type="fixed">
    <origin xyz="0 0 -${base_height_offset}" rpy="0 0 0" />
    <parent link="base_link"/>
    <child link="base_footprint"/>
  </joint>
  
  <link name="base_footprint" />




  <!-- base laser -->
  <joint name="base_laser_joint" type="fixed">
    <origin xyz="${base_laser_offset_x} 0 ${base_laser_size_z/2}" rpy="0 0 0" />
    <parent link="base_link"/>
    <child link="base_laser"/>
  </joint>
  
  <link name="base_laser" type="laser">
    <inertial>
      <mass value="1.0" />
      <origin xyz="0 0 0" />
      <inertia ixx="0.1" ixy="0" ixz="0" iyy="0.1" iyz="0" izz="0.1" />
    </inertial>

    <visual name="base_lvisual">
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry name="base_laser_visual_geom">
	<box size="${base_laser_size_x} ${base_laser_size_y} ${base_laser_size_z}"/>
      </geometry>
      
      <material name="Blue" />
    </visual>

    <collision name="base_lcollision">
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry name="base_laser_collision_geom">
	<box size="${base_laser_size_x} ${base_laser_size_y} ${base_laser_size_z}"/>
      </geometry>
    </collision>

  </link>




</robot>
