// -------------------------------------------------------------------------------
// THIS FILE IS ORIGINALLY GENERATED BY THE DESIGNER.
// YOU ARE ONLY ALLOWED TO MODIFY CODE BETWEEN '///<<< BEGIN' AND '///<<< END'.
// PLEASE MODIFY AND REGENERETE IT IN THE DESIGNER FOR CLASS/MEMBERS/METHODS, ETC.
// -------------------------------------------------------------------------------

#ifndef _BEHAVIAC_BACKGRDFUNC_H_
#define _BEHAVIAC_BACKGRDFUNC_H_

#include "behaviac_headers.h"
#include "BasicLogic.h"
#include "ForegrdFunc.h"
///<<< BEGIN WRITING YOUR CODE FILE_INIT
class BasicLogic;
class ForegrdFunc;

extern BasicLogic* g_BasicLogicAgent;
extern ForegrdFunc* g_ForegrdFuncAgent;
///<<< END WRITING YOUR CODE

class BackgrdFunc : public behaviac::Agent
///<<< BEGIN WRITING YOUR CODE BackgrdFunc
///<<< END WRITING YOUR CODE
{
public:
	BackgrdFunc();
	virtual ~BackgrdFunc();

	BEHAVIAC_DECLARE_AGENTTYPE(BackgrdFunc, behaviac::Agent)

	public: void Pause();

	public: void Resume();

	public: void STOP();

///<<< BEGIN WRITING YOUR CODE CLASS_PART

///<<< END WRITING YOUR CODE
};

///<<< BEGIN WRITING YOUR CODE FILE_UNINIT

///<<< END WRITING YOUR CODE

#endif
