// -------------------------------------------------------------------------------
// THIS FILE IS ORIGINALLY GENERATED BY THE DESIGNER.
// YOU ARE ONLY ALLOWED TO MODIFY CODE BETWEEN '///<<< BEGIN' AND '///<<< END'.
// PLEASE MODIFY AND REGENERETE IT IN THE DESIGNER FOR CLASS/MEMBERS/METHODS, ETC.
// -------------------------------------------------------------------------------

#include "BackgrdFunc.h"

///<<< BEGIN WRITING YOUR CODE FILE_INIT

///<<< END WRITING YOUR CODE

BackgrdFunc::BackgrdFunc()
{
///<<< BEGIN WRITING YOUR CODE CONSTRUCTOR

///<<< END WRITING YOUR CODE
}

BackgrdFunc::~BackgrdFunc()
{
///<<< BEGIN WRITING YOUR CODE DESTRUCTOR

///<<< END WRITING YOUR CODE
}
void BackgrdFunc::Pause()
{
///<<< BEGIN WRITING YOUR CODE Pause
switch (g_BasicLogicAgent->CurrentTask)
{
case Assemble:
g_ForegrdFuncAgent->build_up_action->cancelGoal();
    break;
default:
    break;
}

///<<< END WRITING YOUR CODE
}

void BackgrdFunc::Resume()
{
///<<< BEGIN WRITING YOUR CODE Resume
g_BasicLogicAgent->InputTask=g_BasicLogicAgent->CurrentTask;
// if(g_BasicLogicAgent->InputTask==TaskIndividual::Assemble)
// ROS_INFO("Resume:Input is assemble");
g_BasicLogicAgent->CurrentTask=TaskIndividual::NonTask;
///<<< END WRITING YOUR CODE
}

void BackgrdFunc::STOP()
{
            ROS_INFO("STOP!!!");
///<<< BEGIN WRITING YOUR CODE STOP
switch (g_BasicLogicAgent->CurrentTask)
{
case Assemble:
g_ForegrdFuncAgent->build_up_action->cancelGoal();
    break;
default:
    break;
}

g_BasicLogicAgent->CurrentTask=TaskIndividual::NonTask;
///<<< END WRITING YOUR CODE
}


///<<< BEGIN WRITING YOUR CODE FILE_UNINIT

///<<< END WRITING YOUR CODE
