// -------------------------------------------------------------------------------
// THIS FILE IS ORIGINALLY GENERATED BY THE DESIGNER.
// YOU ARE ONLY ALLOWED TO MODIFY CODE BETWEEN '///<<< BEGIN' AND '///<<< END'.
// PLEASE MODIFY AND REGENERETE IT IN THE DESIGNER FOR CLASS/MEMBERS/METHODS, ETC.
// -------------------------------------------------------------------------------

#ifndef _BEHAVIAC_BASICLOGIC_H_
#define _BEHAVIAC_BASICLOGIC_H_

#include "behaviac_headers.h"

///<<< BEGIN WRITING YOUR CODE FILE_INIT

///<<< END WRITING YOUR CODE

class BasicLogic : public behaviac::Agent
///<<< BEGIN WRITING YOUR CODE BasicLogic
///<<< END WRITING YOUR CODE
{
public:
	BasicLogic();
	virtual ~BasicLogic();

	BEHAVIAC_DECLARE_AGENTTYPE(BasicLogic, behaviac::Agent)

	public: TaskIndividual CurrentTask;

	public: TaskType CurrentType;

	public: TaskIndividual InputTask;

	public: TaskType InputType;

///<<< BEGIN WRITING YOUR CODE CLASS_PART

///<<< END WRITING YOUR CODE
};

///<<< BEGIN WRITING YOUR CODE FILE_UNINIT

///<<< END WRITING YOUR CODE

#endif
