// -------------------------------------------------------------------------------
// THIS FILE IS ORIGINALLY GENERATED BY THE DESIGNER.
// YOU ARE ONLY ALLOWED TO MODIFY CODE BETWEEN '///<<< BEGIN' AND '///<<< END'.
// PLEASE MODIFY AND REGENERETE IT IN THE DESIGNER FOR CLASS/MEMBERS/METHODS, ETC.
// -------------------------------------------------------------------------------

#include "BasicLogic.h"

///<<< BEGIN WRITING YOUR CODE FILE_INIT

///<<< END WRITING YOUR CODE

BasicLogic::BasicLogic()
{
	CurrentTask = NonTask;
	CurrentType = NonType;
	InputTask = NonTask;
	InputType = NonType;
///<<< BEGIN WRITING YOUR CODE CONSTRUCTOR

///<<< END WRITING YOUR CODE
}

BasicLogic::~BasicLogic()
{
///<<< BEGIN WRITING YOUR CODE DESTRUCTOR

///<<< END WRITING YOUR CODE
}

void BasicLogic::Upper_Processing()
{
///<<< BEGIN WRITING YOUR CODE Upper_Processing
if(InputTask==NonTask&&CurrentTask==NonTask&&g_BlackBoardAgent->TaksList.empty()!=1)//单步无任务时取出任务列表中的任务赋给InputTask变量
		{
			InputTask=(TaskIndividual)g_BlackBoardAgent->TaksList.back().mission.mission;

			g_BlackBoardAgent->	goal = g_BlackBoardAgent->TaksList.back().goal.pose;
			
			g_BlackBoardAgent->TaksList.pop_back();
		}

///<<< END WRITING YOUR CODE
}


///<<< BEGIN WRITING YOUR CODE FILE_UNINIT

///<<< END WRITING YOUR CODE
