// ---------------------------------------------------------------------
// THIS FILE IS AUTO-GENERATED BY BEHAVIAC DESIGNER, SO PLEASE DON'T MODIFY IT BY YOURSELF!
// ---------------------------------------------------------------------

#include "../behaviac_types.h"

// -------------------
// Customized enums
// -------------------

BEHAVIAC_BEGIN_ENUM_EX(TaskIndividual, TaskIndividual)
{
	BEHAVIAC_ENUMCLASS_DISPLAY_INFO_EX(L"TaskIndividual", L"");

	BEHAVIAC_ENUM_ITEM_EX(NonTask, "NonTask");
	BEHAVIAC_ENUM_ITEM_EX(March_gps, "March_gps");
	BEHAVIAC_ENUM_ITEM_EX(March_laser, "March_laser");
	BEHAVIAC_ENUM_ITEM_EX(Search, "Search");
	BEHAVIAC_ENUM_ITEM_EX(Remote_Control, "Remote_Control");
	BEHAVIAC_ENUM_ITEM_EX(Assemble, "Assemble");
	BEHAVIAC_ENUM_ITEM_EX(Stop, "Stop");
	BEHAVIAC_ENUM_ITEM_EX(Pause, "Pause");
	BEHAVIAC_ENUM_ITEM_EX(Resume, "Resume");
}
BEHAVIAC_END_ENUM_EX()

BEHAVIAC_BEGIN_ENUM_EX(ForeFuncState, ForeFuncState)
{
	BEHAVIAC_ENUMCLASS_DISPLAY_INFO_EX(L"ForeFuncState", L"");

	BEHAVIAC_ENUM_ITEM_EX(Running, "Running");
	BEHAVIAC_ENUM_ITEM_EX(Success, "Success");
	BEHAVIAC_ENUM_ITEM_EX(Failure, "Failure");
	BEHAVIAC_ENUM_ITEM_EX(Idle, "Idle");
}
BEHAVIAC_END_ENUM_EX()

