// -------------------------------------------------------------------------------
// THIS FILE IS ORIGINALLY GENERATED BY THE DESIGNER.
// YOU ARE ONLY ALLOWED TO MODIFY CODE BETWEEN '///<<< BEGIN' AND '///<<< END'.
// PLEASE MODIFY AND REGENERETE IT IN THE DESIGNER FOR CLASS/MEMBERS/METHODS, ETC.
// -------------------------------------------------------------------------------

#ifndef _BEHAVIAC_BLACKBOARD_H_
#define _BEHAVIAC_BLACKBOARD_H_

#include "behaviac_headers.h"
#include <ros/ros.h>
#include "nav_msgs/OccupancyGrid.h"
#include "nav_msgs/Odometry.h"
#include "robot_msgs/HostCmd.h"
#include "robot_msgs/HostCmdArray.h"
#include "string"
#include <geometry_msgs/PoseStamped.h>
#include "std_msgs/String.h"
#include "BasicLogic.h"
#include "robot_msgs/DebugInfo.h"
///<<< BEGIN WRITING YOUR CODE FILE_INIT

///<<< END WRITING YOUR CODE
class BasicLogic;
extern BasicLogic* g_BasicLogicAgent;
class BlackBoard : public behaviac::Agent
///<<< BEGIN WRITING YOUR CODE BlackBoard
///<<< END WRITING YOUR CODE
{
public:
	BlackBoard();
	virtual ~BlackBoard();

	BEHAVIAC_DECLARE_AGENTTYPE(BlackBoard, behaviac::Agent)

	public: int car_number;

///<<< BEGIN WRITING YOUR CODE CLASS_PART

	public: behaviac::vector<behaviac::string> MissionTable;
    public: void CmdCallback(const robot_msgs::HostCmdArrayConstPtr &msg);                   //**************************RECTIFY
	public:void PubDecisionState(std::string state);
    public:geometry_msgs::Pose GetGoal();
public:
    std::vector<robot_msgs::HostCmd> msgs;
     std::vector<robot_msgs::HostCmd> TaksList;
    //! Goal info
    ros::Publisher debug_pub;
    geometry_msgs::Pose goal;
    // car id 
    std::string decision_state;
private:
    ros::Subscriber goal_sub;
    ros::Subscriber cmd_sub;
    ros::Publisher  decision_state_pub;
///<<< END WRITING YOUR CODE
};

///<<< BEGIN WRITING YOUR CODE FILE_UNINIT

///<<< END WRITING YOUR CODE

#endif
