// -------------------------------------------------------------------------------
// THIS FILE IS ORIGINALLY GENERATED BY THE DESIGNER.
// YOU ARE ONLY ALLOWED TO MODIFY CODE BETWEEN '///<<< BEGIN' AND '///<<< END'.
// PLEASE MODIFY AND REGENERETE IT IN THE DESIGNER FOR CLASS/MEMBERS/METHODS, ETC.
// -------------------------------------------------------------------------------

#ifndef _BEHAVIAC_FOREGRDFUNC_H_
#define _BEHAVIAC_FOREGRDFUNC_H_

#include "behaviac_headers.h"
#include "BlackBoard.h"
#include "BasicLogic.h"
#include "BackgrdFunc.h"
#include "robot_msgs/BuildUpAction.h"
#include "robot_msgs/MarchAction.h"
#include "actionlib/client/simple_action_client.h"
#include <iostream>
#include <string>
#include "memory.h"
///<<< BEGIN WRITING YOUR CODE FILE_INIT
class BasicLogic;
class BackgrdFunc;
class BlackBoard;//类的前向声明

extern BasicLogic* g_BasicLogicAgent;
extern BackgrdFunc* g_BackgrdFuncAgent;
extern BlackBoard* g_BlackBoardAgent;
///<<< END WRITING YOUR CODE

class ForegrdFunc : public behaviac::Agent
///<<< BEGIN WRITING YOUR CODE ForegrdFunc
///<<< END WRITING YOUR CODE
{
public:
	ForegrdFunc();
	virtual ~ForegrdFunc();

	BEHAVIAC_DECLARE_AGENTTYPE(ForegrdFunc, behaviac::Agent)


	public: ForeFuncState fore_func_state;

	public: void Assemble();
	public: void Assemble_FeedbackCallback(const robot_msgs::BuildUpFeedbackConstPtr &feedback);
	public: void Assemble_ActiveCallback(void);
	public: void Assemble_DoneCallback(const actionlib::SimpleClientGoalState &state, const robot_msgs::BuildUpResultConstPtr &result);

	public: void March_gps();
	public: void March_laser();
	public: void March_FeedbackCallback(const robot_msgs::MarchFeedbackConstPtr &feedback);
	public: void March_ActiveCallback(void);
	public: void March_DoneCallback(const actionlib::SimpleClientGoalState &state, const robot_msgs::MarchResultConstPtr &result);


	public: actionlib::SimpleActionClient<robot_msgs::BuildUpAction>* build_up_action;
	public:actionlib::SimpleActionClient<robot_msgs::MarchAction>* gps_march_action;
	public:actionlib::SimpleActionClient<robot_msgs::MarchAction>* laser_march_action;
///<<< BEGIN WRITING YOUR CODE CLASS_PART
private:
    ros::NodeHandle nh;
    
    robot_msgs::BuildUpGoal assemble_goal;
	robot_msgs::MarchGoal march_goal;
///<<< BEGIN WRITING YOUR CODE CLASS_PART

///<<< END WRITING YOUR CODE
};

///<<< BEGIN WRITING YOUR CODE FILE_UNINIT

///<<< END WRITING YOUR CODE

#endif
