// -------------------------------------------------------------------------------
// THIS FILE IS ORIGINALLY GENERATED BY THE DESIGNER.
// YOU ARE ONLY ALLOWED TO MODIFY CODE BETWEEN '///<<< BEGIN' AND '///<<< END'.
// PLEASE MODIFY AND REGENERETE IT IN THE DESIGNER FOR CLASS/MEMBERS/METHODS, ETC.
// -------------------------------------------------------------------------------

#ifndef _BEHAVIAC_GROUPLOGIC_H_
#define _BEHAVIAC_GROUPLOGIC_H_

#include "behaviac_headers.h"
#include "BlackBoard.h"
///<<< BEGIN WRITING YOUR CODE FILE_INIT

///<<< END WRITING YOUR CODE
class BlackBoard;
extern BlackBoard* g_BlackBoardAgent;

class GroupLogic : public behaviac::Agent
///<<< BEGIN WRITING YOUR CODE GroupLogic
///<<< END WRITING YOUR CODE
{
public:
	GroupLogic();
	virtual ~GroupLogic();

	BEHAVIAC_DECLARE_AGENTTYPE(GroupLogic, behaviac::Agent)

	public: behaviac::vector<int> GroupMember;//basiclogic在执行任务时初始化，同一任务的其他参与者为GroupMember

	public: behaviac::vector<ForeFuncState> GroupState;//依赖GroupMember，从BlackBoard中读取State

	public:bool GroupPermission;//组内逻辑的输出信息

	public: void GroupLogicProcessing();

///<<< BEGIN WRITING YOUR CODE CLASS_PART

///<<< END WRITING YOUR CODE
};

///<<< BEGIN WRITING YOUR CODE FILE_UNINIT

///<<< END WRITING YOUR CODE

#endif
